[build]
#target = "riscv32imc-unknown-none-elf"
#target = "riscv32imac-unknown-none-elf"
#target = "xtensa-esp32-none-elf"
target = "thumbv7em-none-eabi"

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[target.'cfg(all(target_arch = "xtensa", target_os = "none"))']
runner  = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Wl,-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

[unstable]
#build-std-features = ["panic_immediate_abort"]

# For host builds and STD targets
build-std = ["core", "alloc", "panic_abort"]
